import logging
import re

# Configure basic logging
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s - %(message)s')
logger = logging.getLogger(__name__)

STOCK_TICKER_DICTIONARY = {
    # Original Stocks
    "apple": "AAPL",
    "apple inc": "AAPL",
    "apple corporation": "AAPL",
    "apple co": "AAPL",
    "aapl": "AAPL",
    "microsoft": "MSFT",
    "microsoft corporation": "MSFT",
    "microsoft inc": "MSFT",
    "msft": "MSFT",
    "amazon": "AMZN",
    "amazon.com": "AMZN",
    "amazon inc": "AMZN",
    "amazon corporation": "AMZN",
    "amzn": "AMZN",
    "nvidia": "NVDA",
    "nvidia corporation": "NVDA",
    "nvidia inc": "NVDA",
    "nvda": "NVDA",
    "alphabet": "GOOGL",
    "google": "GOOGL",
    "alphabet inc": "GOOGL",
    "google inc": "GOOGL",
    "googl": "GOOGL",
    "meta": "META",
    "facebook": "META",
    "meta platforms": "META",
    "meta inc": "META",
    "meta corporation": "META",
    "tesla": "TSLA",
    "tesla inc": "TSLA",
    "tesla motors": "TSLA",
    "tsla": "TSLA",
    "berkshire hathaway": "BRK-B",
    "berkshire": "BRK-B",
    "warren buffett": "BRK-B",
    "brk-b": "BRK-B",
    "jpmorgan chase": "JPM",
    "jpmorgan": "JPM",
    "jp morgan": "JPM",
    "jpm": "JPM",
    "chase": "JPM",
    "visa": "V",
    "visa inc": "V",
    "visa corporation": "V",
    "v": "V",
    "walmart": "WMT",
    "walmart inc": "WMT",
    "wal-mart": "WMT",
    "wmt": "WMT",
    "johnson & johnson": "JNJ",
    "johnson and johnson": "JNJ",
    "jnj": "JNJ",
    "procter & gamble": "PG",
    "procter and gamble": "PG",
    "pg": "PG",
    "mastercard": "MA",
    "mastercard inc": "MA",
    "master card": "MA",
    "ma": "MA",
    "unitedhealth group": "UNH",
    "unitedhealth": "UNH",
    "unh": "UNH",
    "intel": "INTC",
    "intel corporation": "INTC",
    "intc": "INTC",
    "home depot": "HD",
    "home depot inc": "HD",
    "hd": "HD",
    "bank of america": "BAC",
    "bofa": "BAC",
    "bac": "BAC",
    "coca-cola": "KO",
    "coca cola": "KO",
    "coke": "KO",
    "coca-cola company": "KO",
    "ko": "KO",
    "pfizer": "PFE",
    "pfizer inc": "PFE",
    "pfe": "PFE",
    "disney": "DIS",
    "walt disney": "DIS",
    "disney corporation": "DIS",
    "dis": "DIS",
    "verizon": "VZ",
    "verizon communications": "VZ",
    "vz": "VZ",
    "pepsico": "PEP",
    "pepsi": "PEP",
    "pep": "PEP",
    "adobe": "ADBE",
    "adobe inc": "ADBE",
    "adbe": "ADBE",
    "cisco": "CSCO",
    "cisco systems": "CSCO",
    "csco": "CSCO",
    "netflix": "NFLX",
    "netflix inc": "NFLX",
    "nflx": "NFLX",
    "salesforce": "CRM",
    "salesforce inc": "CRM",
    "crm": "CRM",
    "amgen": "AMGN",
    "amgn": "AMGN",
    "boeing": "BA",
    "boeing company": "BA",
    "ba": "BA",
    "starbucks": "SBUX",
    "starbucks corporation": "SBUX",
    "sbux": "SBUX",
    "goldman sachs": "GS",
    "goldman sachs group": "GS",
    "gs": "GS",
    "morgan stanley": "MS",
    "morganstanley": "MS",
    "ms": "MS",
    "chevron": "CVX",
    "chevron corporation": "CVX",
    "cvx": "CVX",
    "exxon mobil": "XOM",
    "exxon": "XOM",
    "xom": "XOM",
    "abbott laboratories": "ABT",
    "abbott": "ABT",
    "abt": "ABT",
    "costco": "COST",
    "costco wholesale": "COST",
    "cost": "COST",
    "merck": "MRK",
    "merck & co": "MRK",
    "mrk": "MRK",
    "eli lilly": "LLY",
    "lilly": "LLY",
    "lly": "LLY",
    "mcdonald's": "MCD",
    "mcdonalds": "MCD",
    "mcd": "MCD",
    "nike": "NKE",
    "nike inc": "NKE",
    "nke": "NKE",
    "ibm": "IBM",
    "ibm corporation": "IBM",
    "qualcomm": "QCOM",
    "qcom": "QCOM",
    "texas instruments": "TXN",
    "txn": "TXN",
    "medtronic": "MDT",
    "mdt": "MDT",
    "honeywell": "HON",
    "hon": "HON",
    "caterpillar": "CAT",
    "cat": "CAT",
    "ups": "UPS",
    "united parcel service": "UPS",
    "lockheed martin": "LMT",
    "lmt": "LMT",
    "3m": "MMM",
    "mmm": "MMM",
    "general electric": "GE",
    "ge": "GE",
    "advanced micro devices": "AMD",
    "amd": "AMD",
    "paypal": "PYPL",
    "pypl": "PYPL",
    "intuit": "INTU",
    "intu": "INTU",
    "applied materials": "AMAT",
    "amat": "AMAT",
    "lam research": "LRCX",
    "lrcx": "LRCX",
    "target": "TGT",
    "tgt": "TGT",
    "cvs health": "CVS",
    "cvs": "CVS",
    "lowe's": "LOW",
    "low": "LOW",
    "union pacific": "UNP",
    "unp": "UNP",
    "deere & company": "DE",
    "john deere": "DE",
    "de": "DE",
    "american express": "AXP",
    "amex": "AXP",
    "axp": "AXP",
    "citigroup": "C",
    "citi": "C",
    "c": "C",
    "wells fargo": "WFC",
    "wfc": "WFC",
    "blackrock": "BLK",
    "blk": "BLK",
    "schwab": "SCHW",
    "charles schwab": "SCHW",
    "at&t": "T",
    "att": "T",
    "t": "T",
    "comcast": "CMCSA",
    "cmcsa": "CMCSA",
    "philip morris": "PM",
    "pm": "PM",
    "altria": "MO",
    "mo": "MO",
    "bristol-myers squibb": "BMY",
    "bmy": "BMY",
    "gilead sciences": "GILD",
    "gild": "GILD",
    "general motors": "GM",
    "gm": "GM",
    "ford": "F",
    "f": "F",
    "delta air lines": "DAL",
    "dal": "DAL",
    "american airlines": "AAL",
    "aal": "AAL",
    "united airlines": "UAL",
    "ual": "UAL",
    "southwest airlines": "LUV",
    "luv": "LUV",
    "cummins": "CMI",
    "cmi": "CMI",
    "emerson electric": "EMR",
    "emr": "EMR",
    "raytheon technologies": "RTX",
    "rtx": "RTX",
    "northrop grumman": "NOC",
    "noc": "NOC",
    "fedex": "FDX",
    "fdx": "FDX",
    "walgreens": "WBA",
    "wba": "WBA",
    "kroger": "KR",
    "kr": "KR",
    "best buy": "BBY",
    "bby": "BBY",
    "macy's": "M",
    "m": "M",
    "kohl's": "KSS",
    "kss": "KSS",
    "nordstrom": "JWN",
    "jwn": "JWN",
    "t-mobile": "TMUS",
    "tmus": "TMUS",
    "verisk analytics": "VRSK",
    "vrsk": "VRSK",
    "s&p global": "SPGI",
    "spgi": "SPGI",
    "moody's": "MCO",
    "mco": "MCO",
    "eog resources": "EOG",
    "eog": "EOG",
    "conocophillips": "COP",
    "cop": "COP",
    "occidental petroleum": "OXY",
    "oxy": "OXY",
    "valero energy": "VLO",
    "vlo": "VLO",
    "marathon petroleum": "MPC",
    "mpc": "MPC",
    "dominion energy": "D",
    "d": "D",
    "duke energy": "DUK",
    "duk": "DUK",
    "southern company": "SO",
    "so": "SO",
    "nextera energy": "NEE",
    "nee": "NEE",
    "american electric power": "AEP",
    "aep": "AEP",
    "exelon": "EXC",
    "exc": "EXC",
    "xcel energy": "XEL",
    "xel": "XEL",
    "consolidated edison": "ED",
    "ed": "ED",
    "public service enterprise": "PEG",
    "peg": "PEG",
    "firstenergy": "FE",
    "fe": "FE",
    "eversource energy": "ES",
    "es": "ES",
    "dte energy": "DTE",
    "dte": "DTE",
    "entergy": "ETR",
    "etr": "ETR",
    "fortis": "FTS",
    "fts": "FTS",
    "ppl corporation": "PPL",
    "ppl": "PPL",
    "centerpoint energy": "CNP",
    "cnp": "CNP",
    "cms energy": "CMS",
    "cms": "CMS",
    "ameren": "AEE",
    "aee": "AEE",
    "nisource": "NI",
    "ni": "NI",
    "aes corporation": "AES",
    "aes": "AES",
    "nucor": "NUE",
    "nue": "NUE",
    "steel dynamics": "STLD",
    "stld": "STLD",
    "reliance steel": "RS",
    "rs": "RS",
    "coterra energy": "CTRA",
    "ctra": "CTRA",
    "devon energy": "DVN",
    "dvn": "DVN",
    "hess": "HES",
    "hes": "HES",
    "marathon oil": "MRO",
    "mro": "MRO",
    "eqt corporation": "EQT",
    "eqt": "EQT",
    "apa corporation": "APA",
    "apa": "APA",
    "halliburton": "HAL",
    "hal": "HAL",
    "schlumberger": "SLB",
    "slb": "SLB",
    "baker hughes": "BKR",
    "bkr": "BKR",
    "kinder morgan": "KMI",
    "kmi": "KMI",
    "williams companies": "WMB",
    "wmb": "WMB",
    "oneok": "OKE",
    "oke": "OKE",
    "enbridge": "ENB",
    "enb": "ENB",
    "tc energy": "TRP",
    "trp": "TRP",
    "sempra energy": "SRE",
    "sre": "SRE",
    "ecolab": "ECL",
    "ecl": "ECL",
    "sherwin-williams": "SHW",
    "shw": "SHW",
    "ppg industries": "PPG",
    "ppg": "PPG",
    "dow inc": "DOW",
    "dow": "DOW",
    "dupont": "DD",
    "dd": "DD",
    "lyondellbasell": "LYB",
    "lyb": "LYB",
    "celanese": "CE",
    "ce": "CE",
    "eastman chemical": "EMN",
    "emn": "EMN",
    "international paper": "IP",
    "ip": "IP",
    "westrock": "WRK",
    "wrk": "WRK",
    "ball corporation": "BALL",
    "ball": "BALL",
    "amcor": "AMCR",
    "amcr": "AMCR",
    "avery dennison": "AVY",
    "avy": "AVY",
    "packaging corp of america": "PKG",
    "pkg": "PKG",
    "sealed air": "SEE",
    "see": "SEE",
    "masco": "MAS",
    "mas": "MAS",
    "fortune brands": "FBHS",
    "fbhs": "FBHS",
    "lennar": "LEN",
    "len": "LEN",
    "d.r. horton": "DHI",
    "dhi": "DHI",
    "pultegroup": "PHM",
    "phm": "PHM",
    "nvr": "NVR",
    "nvr": "NVR",
    "toll brothers": "TOL",
    "tol": "TOL",
    "martin marietta": "MLM",
    "mlm": "MLM",
    "vulcan materials": "VMC",
    "vmc": "VMC",
    "cemex": "CX",
    "cx": "CX",
    "eagle materials": "EXP",
    "exp": "EXP",
    "summit materials": "SUM",
    "sum": "SUM",
    "carrier global": "CARR",
    "carr": "CARR",
    "otis worldwide": "OTIS",
    "otis": "OTIS",
    "trane technologies": "TT",
    "tt": "TT",
    "johnson controls": "JCI",
    "jci": "JCI",
    "lennox international": "LII",
    "lii": "LII",
    "regal rexnord": "RRX",
    "rrx": "RRX",
    "pentair": "PNR",
    "pnr": "PNR",
    "a.o. smith": "AOS",
    "aos": "AOS",
    "watsco": "WSO",
    "wso": "WSO",
    "pool corporation": "POOL",
    "pool": "POOL",
    "grainger": "GWW",
    "gww": "GWW",
    "fastenal": "FAST",
    "fast": "FAST",
    "veritiv": "VRTV",
    "vrtv": "VRTV",
    "msc industrial": "MSM",
    "msm": "MSM",
    "wesco international": "WCC",
    "wcc": "WCC",
    "ferguson": "FERG",
    "ferg": "FERG",
    "hd supply": "HDS",
    "hds": "HDS",
    "siteone landscape": "SITE",
    "site": "SITE",
    "core & main": "CNM",
    "cnm": "CNM",
    "builders firstsource": "BLDR",
    "bldr": "BLDR",
    "topbuild": "BLD",
    "bld": "BLD",
    "mastec": "MTZ",
    "mtz": "MTZ",
    "quanta services": "PWR",
    "pwr": "PWR",
    "emcor group": "EME",
    "eme": "EME",
    "comfort systems": "FIX",
    "fix": "FIX",
    "api group": "APG",
    "apg": "APG",
    "arcosa": "ACA",
    "aca": "ACA",
    "dycom industries": "DY",
    "dy": "DY",
    "primoris services": "PRIM",
    "prim": "PRIM",
    "fluor": "FLR",
    "flr": "FLR",
    "jacobs solutions": "J",
    "j": "J",
    "aecom": "ACM",
    "acm": "ACM",
    "tetra tech": "TTEK",
    "ttek": "TTEK",
    "exponent": "EXPO",
    "expo": "EXPO",
    "coinbase": "COIN",
    "coinbase global": "COIN",
    "coinbase inc": "COIN",
    "coin": "COIN",
    "bitwise bitcoin etf": "BITU",
    "bitu": "BITU",
    "grayscale bitcoin trust": "GBTC",
    "gbtc": "GBTC",
    "ark 21shares bitcoin etf": "ARKB",
    "arkb": "ARKB",
    "ishares bitcoin trust": "IBIT",
    "ibit": "IBIT",
    "proshares bitcoin strategy etf": "BITO",
    "bito": "BITO",
    "riot platforms": "RIOT",
    "riot": "RIOT",
    "marathon digital": "MARA",
    "mara": "MARA",
    "microstrategy": "MSTR",
    "mstr": "MSTR",
    "block inc": "SQ",
    "block": "SQ",
    "sq": "SQ",
    # New Stocks
    "snowflake": "SNOW",
    "snowflake inc": "SNOW",
    "snow": "SNOW",
    "servicenow": "NOW",
    "servicenow inc": "NOW",
    "now": "NOW",
    "micron": "MU",
    "micron technology": "MU",
    "micron inc": "MU",
    "mu": "MU",
    "enphase": "ENPH",
    "enphase energy": "ENPH",
    "enphase inc": "ENPH",
    "enph": "ENPH",
    "draftkings": "DKNG",
    "draftkings inc": "DKNG",
    "dkng": "DKNG",
    "chewy": "CHWY",
    "chewy inc": "CHWY",
    "chwy": "CHWY",
    "booking": "BKNG",
    "booking holdings": "BKNG",
    "booking inc": "BKNG",
    "bkng": "BKNG",
    "zoom": "ZM",
    "zoom video": "ZM",
    "zoom communications": "ZM",
    "zm": "ZM",
    "kraft heinz": "KHC",
    "kraft heinz company": "KHC",
    "khc": "KHC",
    "danaher": "DHR",
    "danaher corporation": "DHR",
    "dhr": "DHR",
    "vf corporation": "VFC",
    "v.f. corporation": "VFC",
    "vfc": "VFC",
    "fox": "FOXA",
    "fox corporation": "FOXA",
    "foxa": "FOXA",
    "hubspot": "HUBS",
    "hubspot inc": "HUBS",
    "hubs": "HUBS",
    "elf beauty": "ELF",
    "e.l.f. beauty": "ELF",
    "elf": "ELF",
    "wix": "WIX",
    "wix.com": "WIX",
    "wix inc": "WIX",
    "wix": "WIX",
    "on holding": "ONON",
    "on holding ag": "ONON",
    "onon": "ONON",
    "crocs": "CROX",
    "crocs inc": "CROX",
    "crox": "CROX",
    "amc": "AMC",
    "amc entertainment": "AMC",
    "amc holdings": "AMC",
    "reddit": "RDDT",
    "reddit inc": "RDDT",
    "rddt": "RDDT",
    "palantir": "PLTR",
    "palantir technologies": "PLTR",
    "pltr": "PLTR",
    "super micro": "SMCI",
    "super micro computer": "SMCI",
    "smci": "SMCI",
    "soundhound": "SOUN",
    "soundhound ai": "SOUN",
    "soun": "SOUN",
    "robinhood": "HOOD",
    "robinhood markets": "HOOD",
    "hood": "HOOD",
    "cava": "CAVA",
    "cava group": "CAVA",
    "cava inc": "CAVA",
    "astera labs": "ALAB",
    "astera": "ALAB",
    "alab": "ALAB",
    "hims": "HIMS",
    "hims & hers": "HIMS",
    "hims inc": "HIMS",
    "tempus": "TEM",
    "tempus ai": "TEM",
    "tem": "TEM",
    "oklo": "OKLO",
    "oklo inc": "OKLO",
    "vistra": "VST",
    "vistra corp": "VST",
    "vst": "VST",
    "rocket lab": "RKLB",
    "rocket lab usa": "RKLB",
    "rklb": "RKLB",
    "d-wave": "QBTS",
    "d-wave quantum": "QBTS",
    "qbts": "QBTS",
    "akero": "AKRO",
    "akero therapeutics": "AKRO",
    "akro": "AKRO",
    "agilysys": "AGYS",
    "agilysys inc": "AGYS",
    "agys": "AGYS",
    "amer sports": "AS",
    "amer sports inc": "AS",
    "as": "AS",
    "zto express": "ZTO",
    "zto": "ZTO",
    "dutch bros": "BROS",
    "dutch brothers": "BROS",
    "bros": "BROS",
    "lucid": "LCID",
    "lucid group": "LCID",
    "lcid": "LCID",
    "wolfspeed": "WOLF",
    "wolfspeed inc": "WOLF",
    "wolf": "WOLF",
    "xpeng": "XPEV",
    "xpeng inc": "XPEV",
    "xpev": "XPEV",
    "ubiquiti": "UI",
    "ubiquiti inc": "UI",
    "ui": "UI",
    "siyata": "SYTA",
    "siyata mobile": "SYTA",
    "syta": "SYTA",
    "nebius": "NBIS",
    "nebius group": "NBIS",
    "nbis": "NBIS",
    "duolingo": "DUOL",
    "duolingo inc": "DUOL",
    "duol": "DUOL",
    "pony ai": "PONY",
    "pony": "PONY",
    "irhythm": "IRTC",
    "irhythm technologies": "IRTC",
    "irtc": "IRTC",
    "aurora": "AUR",
    "aurora innovation": "AUR",
    "aur": "AUR",
    "liberty global": "LBTYA",
    "liberty global a": "LBTYA",
    "lbtya": "LBTYA",
    "liberty global c": "LBTYK",
    "lbtyk": "LBTYK",
    "viavi": "VIAV",
    "viavi solutions": "VIAV",
    "viav": "VIAV",
    "rivian": "RIVN",
    "rivian automotive": "RIVN",
    "rivn": "RIVN",
    "charter": "CHTR",
    "charter communications": "CHTR",
    "chtr": "CHTR",
    "summit therapeutics": "SMMT",
    "summit": "SMMT",
    "smmt": "SMMT",
    "saia": "SAIA",
    "saia inc": "SAIA",
    "appfolio": "APPF",
    "appfolio inc": "APPF",
    "appf": "APPF",
    "avantor": "AVTR",
    "avantor inc": "AVTR",
    "avtr": "AVTR",
    "kinsale": "KNSL",
    "kinsale capital": "KNSL",
    "knsl": "KNSL",
    "dominos": "DPZ",
    "domino’s pizza": "DPZ",
    "dpz": "DPZ",
    "spotify": "SPOT",
    "spotify technology": "SPOT",
    "spot": "SPOT",
    "pinterest": "PINS",
    "pinterest inc": "PINS",
    "pins": "PINS",
    "paymentus": "PAY",
    "paymentus holdings": "PAY",
    "pay": "PAY",
    "guardant": "GH",
    "guardant health": "GH",
    "gh": "GH",
    "nio": "NIO",
    "nio inc": "NIO",
    "asana": "ASAN",
    "asana inc": "ASAN",
    "asan": "ASAN",
    "teradyne": "TER",
    "teradyne inc": "TER",
    "ter": "TER",
    "avis": "CAR",
    "avis budget": "CAR",
    "car": "CAR",
    "henkel": "HENKY",
    "henkel ag": "HENKY",
    "henky": "HENKY",
    "weride": "WRD",
    "weride inc": "WRD",
    "wrd": "WRD",
    "nrg": "NRG",
    "nrg energy": "NRG",
    "quantum computing": "QUBT",
    "qubt": "QUBT",
    "archer": "ACHR",
    "archer aviation": "ACHR",
    "achr": "ACHR",
    "virgin galactic": "SPCE",
    "spce": "SPCE",
    "globant": "GLOB",
    "globant sa": "GLOB",
    "glob": "GLOB",
    "novo nordisk": "NVO",
    "nvo": "NVO",
    "fubotv": "FUBO",
    "fubo": "FUBO",
    "acadia": "ACAD",
    "acadia pharmaceuticals": "ACAD",
    "acad": "ACAD",
    "applied digital": "APLD",
    "apld": "APLD",
    "tss": "TSSI",
    "tss inc": "TSSI",
    "tssi": "TSSI",
    "doximity": "DOCS",
    "doximity inc": "DOCS",
    "docs": "DOCS",
    "foot locker": "FL",
    "fl": "FL",
    "coreweave": "CRWV",
    "coreweave inc": "CRWV",
    "crwv": "CRWV",
    "dicks sporting": "DKS",
    "dick’s sporting goods": "DKS",
    "dks": "DKS",
    "click holdings": "CLIK",
    "clik": "CLIK",
    "new fortress": "NFE",
    "new fortress energy": "NFE",
    "nfe": "NFE",
    "palo alto": "PANW",
    "palo alto networks": "PANW",
    "panw": "PANW",
    "roblox": "RBLX",
    "roblox corporation": "RBLX",
    "rblx": "RBLX",
    "hyperscale": "GPUS",
    "hyperscale data": "GPUS",
    "gpus": "GPUS",
    "canada goose": "GOOS",
    "canada goose holdings": "GOOS",
    "goos": "GOOS",
    "fair isaac": "FICO",
    "fico": "FICO",
    "douglas emmett": "DEI",
    "douglas emmett inc": "DEI",
    "dei": "DEI",
    "antero midstream": "AM",
    "antero": "AM",
    "am": "AM",
    "encore energy": "EU",
    "encore": "EU",
    "eu": "EU",
    "clear secure": "YOU",
    "clear": "YOU",
    "you": "YOU",
    "hsbc": "HSBC",
    "hsbc holdings": "HSBC",
    "first republic": "FRC",
    "frc": "FRC",
    "inhibrx": "INAB",
    "inhibrx inc": "INAB",
    "inab": "INAB",
    "bed bath": "BBBY",
    "bed bath & beyond": "BBBY",
    "bbby": "BBBY",
    "c3.ai": "AI",
    "c3 ai": "AI",
    "ai": "AI",
    "biodesix": "BDSX",
    "biodesix inc": "BDSX",
    "bdsx": "BDSX",
    # New ETFs
    "ishares core s&p 500": "IVV",
    "core s&p 500": "IVV",
    "ivv": "IVV",
    "ishares core total stock market": "ITOT",
    "core total stock market": "ITOT",
    "itot": "ITOT",
    "ishares core msci international": "IXUS",
    "core msci international": "IXUS",
    "ixus": "IXUS",
    "ishares core dividend growth": "DGRO",
    "core dividend growth": "DGRO",
    "dgro": "DGRO",
    "ishares core s&p small cap": "IJR",
    "core s&p small cap": "IJR",
    "ijr": "IJR",
    "ishares core s&p mid cap": "IJH",
    "core s&p mid cap": "IJH",
    "ijh": "IJH",
    "ishares core msci europe": "IEUR",
    "core msci europe": "IEUR",
    "ieur": "IEUR",
    "ishares core international bond": "IAGG",
    "core international bond": "IAGG",
    "iagg": "IAGG",
    "ishares core usd bond market": "IUSB",
    "core usd bond market": "IUSB",
    "iusb": "IUSB",
    "ishares core s&p value": "IUSV",
    "core s&p value": "IUSV",
    "iusv": "IUSV",
    "ishares global 100": "IOO",
    "global 100": "IOO",
    "ioo": "IOO",
    "ishares s&p mid cap 400 value": "IJJ",
    "s&p mid cap 400 value": "IJJ",
    "ijj": "IJJ",
    "ishares top 20 us stocks": "TOPT",
    "top 20 us stocks": "TOPT",
    "topt": "TOPT",
    "ishares msci japan": "EWJ",
    "msci japan": "EWJ",
    "ewj": "EWJ",
    "ishares silver trust": "SLV",
    "ishares silver": "SLV",
    "silver trust": "SLV",
    "slv": "SLV",
    "ishares biotechnology": "IBB",
    "biotechnology": "IBB",
    "ibb": "IBB",
    "ishares semiconductor": "SOXX",
    "semiconductor": "SOXX",
    "soxx": "SOXX",
    "ishares 0-3 month treasury": "SGOV",
    "0-3 month treasury": "SGOV",
    "sgov": "SGOV",
    "vanguard s&p 500": "VOO",
    "s&p 500": "VOO",
    "voo": "VOO",
    "vanguard total stock market": "VTI",
    "total stock market": "VTI",
    "vti": "VTI",
    "invesco qqq": "QQQ",
    "qqq": "QQQ",
    "nasdaq 100": "QQQ",
    "vanguard dividend appreciation": "VIG",
    "dividend appreciation": "VIG",
    "vig": "VIG",
    "schwab dividend equity": "SCHD",
    "dividend equity": "SCHD",
    "schd": "SCHD",
    "spdr s&p biotech": "XBI",
    "s&p biotech": "XBI",
    "xbi": "XBI",
    "first trust biotechnology": "FBT",
    "nyse arca biotechnology": "FBT",
    "fbt": "FBT",
    "invesco biotechnology": "PBE",
    "dynamic biotechnology": "PBE",
    "pbe": "PBE",
    "vaneck biotech": "BBH",
    "biotech": "BBH",
    "bbh": "BBH",
    "vaneck semiconductor": "SMH",
    "semiconductor etf": "SMH",
    "smh": "SMH",
    "vanguard growth": "VGT",
    "growth etf": "VGT",
    "vgt": "VGT",
    # iShares Cryptocurrency ETFs
    "ishares blockchain and tech": "IBLC",
    "blockchain and tech": "IBLC",
    "iblc": "IBLC",
    "ishares ethereum trust": "ETHA",
    "ethereum trust": "ETHA",
    "etha": "ETHA",
    # iShares Gold ETFs
    "ishares gold trust": "IAU",
    "ishares gold": "IAU",
    "gold trust": "IAU",
    "iau": "IAU",
    "ishares gold strategy": "IAUF",
    "gold strategy": "IAUF",
    "iauf": "IAUF",
    "ishares physical gold": "SGLN",
    "physical gold": "SGLN",
    "sgln": "SGLN",
    "ishares gold producers": "SPGP",
    "gold producers": "SPGP",
    "spgp": "SPGP",
    # Similar ETFs (Other Precious Metals and Blockchain)
    "spdr gold shares": "GLD",
    "spdr gold": "GLD",
    "gld": "GLD",
    "aberdeen standard physical gold": "SGOL",
    "physical gold etf": "SGOL",
    "sgol": "SGOL",
    "graniteshares gold trust": "BAR",
    "graniteshares gold": "BAR",
    "bar": "BAR",
    "invesco db precious metals": "DBP",
    "db precious metals": "DBP",
    "dbp": "DBD",
    "amplify transform blockchain": "BLOK",
    "transform blockchain": "BLOK",
    "blok": "BLOK",
    "first trust blockchain": "LEGR",
    "first trust crypto": "LEGR",
    "legr": "LEGR",
}

def get_stock_ticker_suggestions(query: str) -> list:
    """
    Return a list of Yahoo Finance tickers that match the query for stocks or crypto-related stocks/ETFs.
    Args:
        query (str): Asset name (e.g., "apple", "coinbase", "ishares s&p 500", "IAU").
    Returns:
        list: List of matching tickers (e.g., ["AAPL"]). Returns empty list if no match.
    """
    query_lower = query.lower().strip()
    logger.debug(f"Processing stock ticker query: '{query_lower}'")
    suggestions = set()

    # Check for exact ticker match first
    cleaned_query = query_lower.replace("whats the price of", "").replace("stock", "").strip()
    if cleaned_query in [k.lower() for k in STOCK_TICKER_DICTIONARY.values()]:
        ticker = cleaned_query.upper()
        logger.debug(f"Exact ticker match found: '{ticker}' for query '{query}'")
        suggestions.add(ticker)

    # Check dictionary for synonym matches
    for synonym, ticker in STOCK_TICKER_DICTIONARY.items():
        if re.search(r'\b' + re.escape(synonym.lower()) + r'\b', query_lower):
            logger.debug(f"Matched synonym '{synonym}' to ticker '{ticker}'")
            suggestions.add(ticker)

    result = list(suggestions)[:1]
    logger.info(f"Stock ticker suggestions for '{query}': {result}")
    return result