from __future__ import annotations

"""Qt binding bridge for Somi's desktop UI."""

try:
    from PySide6.QtCore import QEasingCurve, QPointF, QRect, QRectF, QPropertyAnimation, QThread, QTimer, QUrl, Qt, Signal, Slot
    from PySide6.QtGui import QColor, QFont, QIcon, QPainter, QPixmap, QTextDocument, QTransform
    from PySide6.QtWidgets import (
        QAbstractItemView,
        QApplication,
        QCheckBox,
        QComboBox,
        QDialog,
        QDoubleSpinBox,
        QFileDialog,
        QFrame,
        QGraphicsOpacityEffect,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMessageBox,
        QPushButton,
        QSlider,
        QSpinBox,
        QSplitter,
        QTabWidget,
        QTableWidget,
        QTableWidgetItem,
        QTextEdit,
        QTreeWidget,
        QTreeWidgetItem,
        QVBoxLayout,
        QWidget,
    )
    QT_BINDING = "PySide6"
except ImportError:  # pragma: no cover
    from PyQt6.QtCore import QEasingCurve, QPointF, QRect, QRectF, QPropertyAnimation, QThread, QTimer, QUrl, Qt, pyqtSignal as Signal, pyqtSlot as Slot
    from PyQt6.QtGui import QColor, QFont, QIcon, QPainter, QPixmap, QTextDocument, QTransform
    from PyQt6.QtWidgets import (
        QAbstractItemView,
        QApplication,
        QCheckBox,
        QComboBox,
        QDialog,
        QDoubleSpinBox,
        QFileDialog,
        QFrame,
        QGraphicsOpacityEffect,
        QHBoxLayout,
        QHeaderView,
        QInputDialog,
        QLabel,
        QLineEdit,
        QListWidget,
        QListWidgetItem,
        QMainWindow,
        QMessageBox,
        QPushButton,
        QSlider,
        QSpinBox,
        QSplitter,
        QTabWidget,
        QTableWidget,
        QTableWidgetItem,
        QTextEdit,
        QTreeWidget,
        QTreeWidgetItem,
        QVBoxLayout,
        QWidget,
    )
    QT_BINDING = "PyQt6"

pyqtSignal = Signal
pyqtSlot = Slot

__all__ = [
    "QAbstractItemView",
    "QApplication",
    "QCheckBox",
    "QColor",
    "QComboBox",
    "QDialog",
    "QDoubleSpinBox",
    "QEasingCurve",
    "QFileDialog",
    "QFont",
    "QFrame",
    "QGraphicsOpacityEffect",
    "QHBoxLayout",
    "QHeaderView",
    "QIcon",
    "QInputDialog",
    "QLabel",
    "QLineEdit",
    "QListWidget",
    "QListWidgetItem",
    "QMainWindow",
    "QMessageBox",
    "QPainter",
    "QPixmap",
    "QPointF",
    "QPropertyAnimation",
    "QPushButton",
    "QRect",
    "QRectF",
    "QSlider",
    "QSpinBox",
    "QSplitter",
    "QTabWidget",
    "QTableWidget",
    "QTableWidgetItem",
    "QTextDocument",
    "QTextEdit",
    "QThread",
    "QTimer",
    "QTransform",
    "QTreeWidget",
    "QTreeWidgetItem",
    "QUrl",
    "QVBoxLayout",
    "QWidget",
    "QT_BINDING",
    "Qt",
    "Signal",
    "Slot",
    "pyqtSignal",
    "pyqtSlot",
]
