"""Assistant continuity and proactive behavior limits."""

DAILY_PROACTIVE_MESSAGE_BUDGET = 3
QUIET_HOURS_START = 22  # local hour inclusive
QUIET_HOURS_END = 7  # local hour exclusive
MAX_TRACKED_ACTIVE_ITEMS = 12
MAX_UNRESOLVED_LOOPS = 20
MIN_PROACTIVE_SUGGESTION_INTERVAL_MINUTES = 180
RESURFACING_THRESHOLD_HOURS = 24
