# AUTO-GENERATED BY DATA ANALYSIS AGENT — Manual Edit
# Generated: 2026-02-08 21:18:25

from typing import Dict, List

EXTRACTION_FIELDS: List[str] = ['Name', 'Date of Birth', 'ID Number', 'Seizure Type', 'CT', 'MRI', 'EEG', 'Previous Surgeries', 'Current Medications', 'Complications', 'Phone Number', 'Age at Diagnosis']

EXAMPLE_ENTRY: Dict[str, str] = {'Name': 'John Doe', 'Date of Birth': '01/01/2001', 'ID Number': '123456789', 'Seizure Type': 'Focal Aware Motor', 'CT': 'Nil Findings', 'MRI': 'Frontal Lobe Anomaly', 'EEG': 'Frontal Lobe Inter-Epileptiform Discharges', 'Previous Surgeries': 'Front Lobe Venous Lesion Resection', 'Current Medications': 'CBZ', 'Complications': 'Language Impairment', 'Phone Number': '00000000', 'Age at Diagnosis': '01'}

POST_PROCESSING: Dict[str, callable] = {}

OUTPUT_COLUMNS: List[str] = EXTRACTION_FIELDS.copy()
