# AUTO-GENERATED BY DATA ANALYSIS AGENT — Manual Edit
# Generated: 2025-12-09 20:51:58

from typing import Dict, List

EXTRACTION_FIELDS: List[str] = ['Name', 'Date of Birth', 'ID Number', 'Seizure Type', 'CT', 'MRI', 'EEG', 'Previous Surgeries', 'Current Medications', 'Complications', 'Phone Number', 'Age at Diagnosis']

EXAMPLE_ENTRY: Dict[str, str] = {'Name': 'John Doe', 'Date of Birth': '19/09/1994', 'ID Number': '865453', 'Seizure Type': 'Focal Aware Motor', 'CT': 'Nil Findings', 'MRI': 'Frontal Lobe Venous Anomaly', 'EEG': 'Frontal Lobe Inter-Epileptiform Discharges', 'Previous Surgeries': 'Front Lobe Venous Lesion Resection', 'Current Medications': 'Carbamazepine 200mg po bd', 'Complications': 'Language Impairment', 'Phone Number': '4249659', 'Age at Diagnosis': '12'}

POST_PROCESSING: Dict[str, callable] = {}

OUTPUT_COLUMNS: List[str] = EXTRACTION_FIELDS.copy()
