SYSTEM_TIMEZONE = "America/New_York"

"""Heartbeat-related runtime settings."""

HEARTBEAT_ENABLED = True
HEARTBEAT_MODE = "MONITOR"  # OFF | MONITOR | ASSIST
HEARTBEAT_TICK_SECONDS = 10
HB_UI_HEARTBEAT_UPDATE_SECONDS = 2
HB_ALIVE_BREADCRUMB_MINUTES = 30

HB_MAX_EVENTS_BUFFER = 200
HB_MAX_UI_EVENTS_PER_DRAIN = 25
HB_EVENT_DEDUPE_COOLDOWN_SECONDS = 300

HEARTBEAT_QUIET_HOURS = ("22:00", "05:00")
HB_LOG_PATH = "sessions/logs/heartbeat.log"

HB_FEATURE_DAILY_GREETING = True
HEARTBEAT_DAILY_GREETING_TIME = "05:00"
HB_GREETING_INCLUDE_QUOTE = True
HB_GREETING_INCLUDE_WEATHER = True
HB_GREETING_INCLUDE_NEWS_URGENT = False
HB_GREETING_MAX_WORDS = 80
HB_GREETING_CHANNEL = "activity"

HB_FEATURE_WEATHER_WARN = True
HB_WEATHER_CHECK_MINUTES = 45
HB_WEATHER_WARN_DEDUPE_HOURS = 8
HB_WEATHER_FRESHNESS_MINUTES = 180
HB_WEATHER_THRESHOLDS = {
    "precip_prob": 0.70,
    "rain_mm": 10,
    "wind_kph": 45,
    "heat_c": 35,
    "cold_c": 5,
    "storm_keywords": ["storm", "thunderstorm", "hurricane", "tropical storm", "flood", "hail", "severe"],
}
HB_WEATHER_FAIL_SILENT = True

HB_FEATURE_DELIGHT = True
HB_DELIGHT_FREQUENCY = "3_per_week"  # daily | 3_per_week | weekly
HB_DELIGHT_QUIET_HOURS_RESPECT = True
HB_DELIGHT_COOLDOWN_HOURS = 24
HB_DELIGHT_AVOID_AFTER_GREETING_MINUTES = 60
HB_DELIGHT_MAX_WORDS = 50
HB_DELIGHT_SOURCES = ["local_jokes", "local_facts", "agentpedia_fact", "interest_snippet"]

HB_FEATURE_NEWS_URGENT = False
HB_NEWS_DISABLED = True

HB_FEATURE_AGENTPEDIA_GROWTH = True
HB_AGENTPEDIA_GROWTH_FREQUENCY = "weekly"  # weekly | 3_per_week | daily
HB_AGENTPEDIA_GROWTH_FREQUENCY_MODE = "explicit"  # explicit | role_default
HB_AGENTPEDIA_FACTS_PER_RUN = 2
HB_AGENTPEDIA_ANNOUNCE_UPDATES = False
HB_AGENTPEDIA_MIN_CONFIDENCE_TO_COMMIT = 0.70
HB_AGENTPEDIA_FAIL_SILENT = True

CAREER_ROLE = None
USER_INTERESTS = []
HB_FEATURE_CAREER_ROLE = True

HB_FEATURE_REMINDERS = True
HB_FEATURE_GOAL_NUDGES = True
HB_GOAL_NUDGE_INTERVAL_MINUTES = 240
