"""Memory-related runtime settings."""

MEMORY_MODEL = "phi3:3.8b"
MEMORY_STORE_DIR = "memory_store"
USE_MEMORY3 = True
MEMORY_DB_PATH = "memory_store/memory.db"
MEMORY_PINNED_MD_PATH = "memory_store/MEMORY.md"
MEMORY_MAX_TOTAL_CHARS = 2200
MEMORY_MAX_PINNED_LINES = 10
MEMORY_MAX_FACT_LINES = 10
MEMORY_MAX_SKILL_LINES = 6
MEMORY_LINE_MAX_CHARS = 160
MEMORY_VOLATILE_TTL_HOURS = 48
MEMORY_EXTRACTION_ENABLED = True
MEMORY_CONF_MIN = 0.65
MEMORY_SUMMARY_EVERY_N_TURNS = 8
EMBEDDING_MODEL = "nomic-embed-text"
EMBEDDING_DIM = 768
SQLITE_VEC_ENABLED = True
SQLITE_VEC_EXTENSION_PATH = ""
MEMORY_DEBUG = True
USE_VECTOR_INDEX = False
VECTOR_INDEX_BACKEND = "zvec"  # zvec|null
MEMORY_AUTO_CAPTURE_HIGH_VALUE = False
HISTORY_SUMMARY_MODEL = MEMORY_MODEL
DISABLE_MEMORY_FOR_FINANCIAL = True
