from __future__ import annotations

ROLE_PROFILES: dict[str, dict] = {
    "Internal Medicine": {
        "topic_seeds": [
            "hypertension emergencies",
            "atrial fibrillation anticoagulation basics",
            "dka protocol overview",
            "pancreatitis workup essentials",
            "sepsis bundle fundamentals",
            "ckd staging essentials",
            "anemia diagnostic algorithm",
            "heart failure medication classes",
            "community acquired pneumonia antibiotics principles",
            "stroke secondary prevention basics",
        ],
        "domains": ["biomed"],
        "source_allowlist": ["nih.gov", "who.int", "cdc.gov"],
        "avoid_topics": ["breaking", "latest", "celebrity"],
        "nugget_style": "clinical_pearl",
        "growth_frequency_default": "3_per_week",
        "tone_notes": "concise evidence-based clinical pearls",
    },
    "Radiology": {
        "topic_seeds": [
            "ct head bleed patterns",
            "pe findings on ctpa",
            "appendicitis ct indicators",
            "fast exam interpretation basics",
            "mri spine red flags",
            "lung nodule guideline overview",
            "msk fracture sign patterns",
            "abdominal aortic aneurysm imaging basics",
        ],
        "domains": ["biomed"],
        "source_allowlist": ["acr.org", "radiologyinfo.org"],
        "avoid_topics": ["breaking", "latest", "celebrity"],
        "nugget_style": "imaging_pearl",
        "growth_frequency_default": "3_per_week",
        "tone_notes": "pattern-recognition and reporting clarity",
    },
    "DevOps": {
        "topic_seeds": [
            "docker image hardening basics",
            "systemd service reliability patterns",
            "observability fundamentals",
            "ci cd pipeline design basics",
            "secrets management principles",
            "nginx reverse proxy essentials",
            "log rotation best practices",
            "api rate limiting basics",
            "backup and restore validation basics",
        ],
        "domains": ["engineering"],
        "source_allowlist": ["kubernetes.io", "nginx.org", "cloudflare.com"],
        "avoid_topics": ["breaking", "latest", "celebrity"],
        "nugget_style": "dev_tip",
        "growth_frequency_default": "weekly",
        "tone_notes": "operational reliability and safety",
    },
    "Gaming": {
        "topic_seeds": [
            "aim training routines",
            "ranked mindset basics",
            "gaming ergonomics essentials",
            "latency and ping basics",
            "game patch note reading strategy",
            "core game design feedback loops",
        ],
        "domains": ["entertainment"],
        "source_allowlist": [],
        "avoid_topics": ["breaking", "latest", "celebrity"],
        "nugget_style": "gaming_tip",
        "growth_frequency_default": "weekly",
        "tone_notes": "practical and performance-oriented",
    },
    "Anime": {
        "topic_seeds": [
            "animation production pipeline basics",
            "common anime character archetypes",
            "anime studio history overview",
            "storytelling tropes in anime",
            "anime ost composition fundamentals",
        ],
        "domains": ["entertainment"],
        "source_allowlist": [],
        "avoid_topics": ["breaking", "latest", "celebrity", "gossip"],
        "nugget_style": "anime_trivia",
        "growth_frequency_default": "weekly",
        "tone_notes": "evergreen medium literacy",
    },
    "General": {
        "topic_seeds": [
            "space exploration fundamentals",
            "basic biology facts",
            "productive micro habits",
            "memory and learning basics",
            "everyday risk management",
            "evidence literacy basics",
        ],
        "domains": ["general"],
        "source_allowlist": [],
        "avoid_topics": ["breaking", "latest", "celebrity"],
        "nugget_style": "fun_fact",
        "growth_frequency_default": "weekly",
        "tone_notes": "neutral concise evergreen",
    },
}
